apiVersion: apps/v1
kind: Deployment
metadata:
  name: replenishments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: replenishments
  template:
    metadata:
      labels:
        app: replenishments
    spec:
      containers:
        - name: replenishments
          image: yevhen24/replenishments
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                 fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: banking
            - name: MONGO_URI
              value: 'mongodb://replenishments-mongo-srv:27017/replenishments'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: replenishments-srv
spec:
  selector:
    app: replenishments
  ports:
    - name: replenishments
      protocol: TCP
      port: 3000
      targetPort: 3000